// vim set: syntax=asciidoc

== Aufgabe 1: Erkennen von IPv4 Adressen

Sie erhalten eine CSV Datei in der IPv4 Adressen eingetragen sind. +
Lesen Sie die Datei mit Python3 ein. Das Program soll nun für jede Zeile die unten aufgeführten Fragen beantworten. +

1. Handelt es sich bei der aktuellen Zeile um eine IPv4 Host Adresse?
2. Handelt es sich bei der aktuellen Zeile um eine IPv4 Netzmaske?
3. Handelt es sich bei der aktuellen Zeile um eine IPv4 Adresse mit einer Netzmaske in Kurzschreibweise?
4. Handelt es sich bei der aktuellen Zeile um eine IPv4 Broadcast Adresse?
5. Handelt es sich bei der aktuellen Zeile um eine private IPv4 Adresse?
6. Handelt es sich bei der aktuellen Zeile um eine IPv6 Adresse?
7. Handelt es sich bei der aktuellen Zeile um einen gültigen Wert?


Die Aufgaben sind nach Schwierigkeitsgrad gestellt. Schwerere Aufgaben folgen den leichteren Aufgaben. +
In der CSV sind mehrere Spalten enthalten. In der ersten Zeile steht eine Beschreibung der einzelnen Spalten.

[source.bash]
.+network_stuff.csv+
----
address;private;network;broadcast;netmask;hosts;ipv6
138.201.41.13;;;;;
192.168.12.22;;;;;
some garbage;;;;;
172.32.9.31;;;;;
8.8.8.8;;;;;
192.168.23.0/24;;;;;
13.13.13.15/28;;;;;
10.0.12.23/12;;;;;
192.168.0.8/29;;;;;
7.7.7.7.7;;;;;
192.168.23.63/30;;;;;
255.255.255.240;;;;;
0.0.0.0;;;;;
fe80::f486:739b:e9e5:23f6/64;;;;;
127.0.1.53;;;;;
225.255.255.240/28;;;;;
192.168.178.21/24;;;;;
192.168.123.255;;;;;
----

== Aufgabe 1.1: Schreiben einer Funktion

Das obige Programm erkennt zuverlässig IPv4 Adressen. Diese Funktionalität ist für Sie wertvoll. Lagern Sie die obige Funktionalität daher in eine Funktion aus. Die Funktion soll als Argument die IP-Adresse erhalten. Die Funktion soll eine der folgenden Antworten geben:

* öffentliche IPv4 Adresse
* private IPv4 Adresse
* Netzwerkadresse
* Broadcast
* Broadcast
* Netzmaske
* IPv6 Adresse
* etwas Müll

